Scenario Manager: add ports_per_vswitch in InternalTopologyConfig
futurewei-cloud/merak pull request #95
Opened 2022-09-01 00:39 UTC by cj-chung

This PR make following change:
1) add `ports_per_vswitch` to `InternalTopologyConfig` protobuf
2) make the corresponding change in scenario manager's `entities.TopoConfig`
3) make the corresponding change in the constructTopology message.

2022-09-01 17:22 UTC, phudtran requested changes
Just some typos.

2022-09-02 20:55 UTC, cj-chung commented on services/scenario-manager/handler/message.go
> +	conf.PortsPerVswtich = uint32(topo.PortsPerVSwitch)
fixed the typo

2022-09-02 20:55 UTC, cj-chung commented on api/proto/v1/topology.proto
> +    uint32 ports_per_vswtich = 11;
fix the typo

2022-09-02 21:07 UTC, phudtran approved these changes
LGTM

2022-09-02 21:40 UTC, merged